# Generated by Django 5.2.7 on 2026-02-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/%Y/%m/%d/"),
        ),
    ]
