# Generated by Django 5.2.7 on 2026-02-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_featured_image"),
    ]

    operations = []
